M sync

diff --git a/sync b/sync
--- a/sync
+++ b/sync
@@ -6,6 +6,18 @@ echo "_____________________________
         GIT AUTOMATION         
 _____________________________"
 
+#Pulling the latest code from the branch before making any changes...
+echo -e "[+]Pulling the branch";
+    read -p "[+]Enter the pull branch name: " branch;
+    git pull --rebase origin $branch;
+    if [ $? -eq 0 ];
+    then
+        echo -e "Git pull was successful on [$branch]";
+    else
+        echo -e "Git pull failed! on [$branch]";
+    fi
+
+# Adding new changes to the repo
 gstatus=`git status --porcelain`
 
 if [ ${#gstatus} -ne 0 ]
